-- MySQL Script generated by MySQL Workbench
-- Sistema de Gestão de Livros - Berg Lindo
-- Banco de Dados Completo
-- Última atualização: 2025

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalhoberg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalhoberg` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `trabalhoberg` ;

-- -----------------------------------------------------
-- Table `trabalhoberg`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhoberg`.`autores` (
  `id_autores` INT NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(50) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id_autores`),
  INDEX `idx_nome_autor` (`nome_autor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `trabalhoberg`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhoberg`.`series` (
  `id_series` INT NOT NULL AUTO_INCREMENT,
  `nome_serie` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL,
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id_series`),
  INDEX `idx_nome_serie` (`nome_serie` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `trabalhoberg`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhoberg`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `senha` VARCHAR(255) NULL,
  `tipo_usuario` ENUM('admin', 'leitor') NOT NULL DEFAULT 'leitor',
  `data_cadastro` DATE NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  INDEX `idx_nome_usuario` (`nome` ASC),
  INDEX `idx_email` (`email` ASC),
  INDEX `idx_tipo_usuario` (`tipo_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `trabalhoberg`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhoberg`.`livros` (
  `id_livros` INT NOT NULL AUTO_INCREMENT,
  `titulos` VARCHAR(255) NOT NULL,
  `ano_publicado` YEAR NULL,
  `imagem_capa` VARCHAR(255) NULL,
  `autores_id_autores` INT NOT NULL,
  `series_id_series` INT NULL,
  PRIMARY KEY (`id_livros`, `autores_id_autores`),
  INDEX `fk_livros_autores_idx` (`autores_id_autores` ASC),
  INDEX `fk_livros_series_idx` (`series_id_series` ASC),
  INDEX `idx_titulo` (`titulos` ASC),
  INDEX `idx_ano` (`ano_publicado` ASC),
  CONSTRAINT `fk_livros_autores`
    FOREIGN KEY (`autores_id_autores`)
    REFERENCES `trabalhoberg`.`autores` (`id_autores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_series`
    FOREIGN KEY (`series_id_series`)
    REFERENCES `trabalhoberg`.`series` (`id_series`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Dados de Exemplo (Opcional - Descomente se quiser dados de teste)
-- -----------------------------------------------------

/*
-- Inserir autores de exemplo
INSERT INTO `autores` (`nome_autor`, `nacionalidade`, `data_cadastro`) VALUES
('Clarice Lispector', 'Brasil', CURDATE()),
('Machado de Assis', 'Brasil', CURDATE()),
('Jorge Amado', 'Brasil', CURDATE()),
('Guimarães Rosa', 'Brasil', CURDATE());

-- Inserir séries de exemplo
INSERT INTO `series` (`nome_serie`, `descricao`, `data_cadastro`) VALUES
('Harry Potter', 'Série de livros de fantasia sobre um jovem bruxo', CURDATE()),
('O Senhor dos Anéis', 'Trilogia épica de fantasia', CURDATE());

-- Inserir livros de exemplo
INSERT INTO `livros` (`titulos`, `ano_publicado`, `autores_id_autores`, `series_id_series`) VALUES
('A Hora da Estrela', 1977, 1, NULL),
('Dom Casmurro', 1899, 2, NULL),
('Capitães da Areia', 1937, 3, NULL),
('Grande Sertão: Veredas', 1956, 4, NULL);
*/

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
